@echo off
setlocal enabledelayedexpansion

for /F "tokens=2" %%i in ('date /t') do set mydate=%%i
set mytime=%time%

(
  echo package frc.robot.commands.auto;
  echo.
  echo import java.util.List;
  echo.
  echo import edu.wpi.first.math.geometry.Pose2d;
  echo import edu.wpi.first.math.geometry.Rotation2d;
  echo import edu.wpi.first.math.trajectory.Trajectory;
  echo import edu.wpi.first.math.trajectory.TrajectoryGenerator;
  echo import frc.robot.Constants;
  echo.
  echo /**
  echo  * THIS FILE IS AUTO-GENERATED BY createPathFiles.bat
  echo  * DO NOT MODIFY IT
  echo  * %mydate% %mytime%
  echo  * Use these to build full auto routines
  echo  */
  echo public class GeneratedPaths {
  echo.
  for /f %%f in ('dir /b PathWeaver\Paths') do (
    echo   public static final Trajectory %%f = TrajectoryGenerator.generateTrajectory(
    echo     List.of(
    set /A step=1
    set lines=0
    for /f "usebackq" %%b in (`type "PathWeaver\Paths\%%f" ^| find "" /v /c`) do (
      set lines=%%b
      set /a "lines=!lines!-1"
    )
    set /a "reversed=false"
    for /F "skip=1 usebackq tokens=1-6 delims=," %%g in ("PathWeaver\Paths\%%f") do (
      if !step! equ !lines! (
      echo       new Pose2d(%%g, %%h, new Rotation2d(%%i, %%j^)^)
      ) else (
      echo       new Pose2d(%%g, %%h, new Rotation2d(%%i, %%j^)^),
      )
      set /A step+=1
      set reversed=%%l
    )
    echo     ^),
    if !reversed! == true (
      echo     Constants.DRIVETRAIN.TRAJECTORY_CONFIG_REVERSED
    ) else (
      echo     Constants.DRIVETRAIN.TRAJECTORY_CONFIG
    )
    echo   ^);
    echo.
  )
  echo }
) > src\main\java\frc\robot\commands\auto\GeneratedPaths.java

(
  echo package frc.robot.commands.auto;
  echo.
  echo import edu.wpi.first.wpilibj2.command.InstantCommand;
  echo import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
  echo import frc.robot.RobotContainer;
  echo import frc.robot.commands.drivetrain.DrivePath;
  echo.
  echo /**
  echo  * THIS FILE IS AUTO-GENERATED BY createPathFiles.bat
  echo  * DO NOT MODIFY IT
  echo  * %mydate% %mytime%
  echo  * Use these as examples to add additional steps into
  echo  */
  echo public class GeneratedAutos {
  for /f %%f in ('dir /b PathWeaver\Autos') do (
    echo   public class %%f extends SequentialCommandGroup {
    echo     public %%f(^) {
    echo       addCommands(
    set /A step2=1
    set lines=0
    set "file=PathWeaver\Autos\%%f"
    for /f "usebackq" %%b in (`type "!file!" ^| find "" /v /c`) do (
      set lines=%%b
      set /a "lines=!lines!"
    )
    for /F "usebackq tokens=*" %%g in ("!file!") do (
      if !step2! equ 1 (
        echo         new InstantCommand((^) ^-^> { RobotContainer.DRIVETRAIN.resetPose(GeneratedPaths.%%g.getInitialPose(^)^); }^), 
      )
      if !step2! equ !lines! (
      echo         new DrivePath(GeneratedPaths.%%g^)
      ) else (
      echo         new DrivePath(GeneratedPaths.%%g^),
      )
      set /A step2+=1
    )
    echo       ^);
    echo     ^}
    echo   ^}
    echo.
  )
  echo }

) > src\main\java\frc\robot\commands\auto\GeneratedAutos.java
exit