package frc.robot.commands.auto;

import java.util.List;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.trajectory.Trajectory;
import edu.wpi.first.math.trajectory.TrajectoryGenerator;
import frc.robot.Constants;

/**
 * THIS FILE IS AUTO-GENERATED BY createPathFiles.bat
 * DO NOT MODIFY IT
 * 03/13/2022 20:28:10.02
 * Use these to build full auto routines
 */
public class GeneratedPaths {

  public static final Trajectory LeftCargo_Steal = TrajectoryGenerator.generateTrajectory(
    List.of(
      new Pose2d(5.205164369747899, -2.1728449210084038, new Rotation2d(-0.5142462655462188, 0.3973721142857143)),
      new Pose2d(5.867451226890755, -1.0586446789915962, new Rotation2d(0.864868719327732, 0.5765791462184875))
    ),
    Constants.DRIVETRAIN.TRAJECTORY_CONFIG
  );

  public static final Trajectory LeftGrab_LeftCargo = TrajectoryGenerator.generateTrajectory(
    List.of(
      new Pose2d(6.194698850420168, -2.8507149983193276, new Rotation2d(-0.5220378756302528, 0.32724762352941195)),
      new Pose2d(5.212955979831933, -2.16505331092437, new Rotation2d(-1.2076995630252108, 0.8492854991596632))
    ),
    Constants.DRIVETRAIN.TRAJECTORY_CONFIG
  );

  public static final Trajectory MidCargoFromRight_Terminal = TrajectoryGenerator.generateTrajectory(
    List.of(
      new Pose2d(5.296904294930875, -6.532879118677148, new Rotation2d(-2.596114211547844, 1.982762997451884)),
      new Pose2d(1.2824657058281366, -6.931005259745188, new Rotation2d(-0.5142462655462187, -0.4147147302792078))
    ),
    Constants.DRIVETRAIN.TRAJECTORY_CONFIG
  );

  public static final Trajectory MidCargo_Terminal = TrajectoryGenerator.generateTrajectory(
    List.of(
      new Pose2d(5.363258651775548, -6.2011073344537815, new Rotation2d(-1.045081120303605, -0.8543123443751703)),
      new Pose2d(1.278192887394957, -6.9257270722689075, new Rotation2d(-1.8662162862564384, -1.6505646265112484))
    ),
    Constants.DRIVETRAIN.TRAJECTORY_CONFIG
  );

  public static final Trajectory MidStart_MidCargo = TrajectoryGenerator.generateTrajectory(
    List.of(
      new Pose2d(6.482988423529411, -5.554403697478992, new Rotation2d(-0.6467036369747907, -0.3662056739495805)),
      new Pose2d(5.354964357169964, -6.209401629059367, new Rotation2d(-0.6801321576579014, -0.5557177385741383))
    ),
    Constants.DRIVETRAIN.TRAJECTORY_CONFIG
  );

  public static final Trajectory RightCargo_MidCargo = TrajectoryGenerator.generateTrajectory(
    List.of(
      new Pose2d(7.6939554359447, -7.7272575418812695, new Rotation2d(-0.06635435684467339, -0.24882883816752432)),
      new Pose2d(5.305198589536459, -6.5245999999999995, new Rotation2d(-1.5427387966386554, 1.1694955393873672))
    ),
    Constants.DRIVETRAIN.TRAJECTORY_CONFIG
  );

  public static final Trajectory Right_RightCargo = TrajectoryGenerator.generateTrajectory(
    List.of(
      new Pose2d(8.025727220168067, -6.4831133510436425, new Rotation2d(0.033177178422336695, -0.630366390024399)),
      new Pose2d(7.6939554359447, -7.7272575418812695, new Rotation2d(-0.13270871368934678, -0.555717738574141))
    ),
    Constants.DRIVETRAIN.TRAJECTORY_CONFIG
  );

  public static final Trajectory Right_RightCargo_MidCargo = TrajectoryGenerator.generateTrajectory(
    List.of(
      new Pose2d(8.025727220168067, -6.4831133510436425, new Rotation2d(0.033177178422336695, -0.630366390024399)),
      new Pose2d(7.893269848739496, -7.712679690756302, new Rotation2d(-0.5609959260504205, -0.9038267697479005)),
      new Pose2d(5.290872080672268, -6.512771737815125, new Rotation2d(-0.7869526184873958, 0.5843707563025209))
    ),
    Constants.DRIVETRAIN.TRAJECTORY_CONFIG
  );

  public static final Trajectory Terminal_Shoot = TrajectoryGenerator.generateTrajectory(
    List.of(
      new Pose2d(1.2859844974789907, -6.917935462184875, new Rotation2d(-1.6505646265112497, -1.45150155597723)),
      new Pose2d(5.396435830197885, -5.496092292979128, new Rotation2d(-1.7749790455950123, -0.8791952281919206))
    ),
    Constants.DRIVETRAIN.TRAJECTORY_CONFIG_REVERSED
  );

}
