package frc.robot.commands.auto;

import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import frc.robot.RobotContainer;
import frc.robot.commands.drivetrain.DriveTrajectory;

/**
 * THIS FILE IS AUTO-GENERATED BY createPathFiles.bat
 * DO NOT MODIFY IT
 * 03/13/2022 20:28:10.02
 * Use these as examples to add additional steps into
 */
public class GeneratedAutos {
  public class Left2Cargo extends SequentialCommandGroup {
    public Left2Cargo() {
      addCommands(
        new InstantCommand(() -> { RobotContainer.DRIVETRAIN.resetPose(GeneratedPaths.LeftGrab_LeftCargo.getInitialPose()); }), 
        new DriveTrajectory(GeneratedPaths.LeftGrab_LeftCargo)
      );
    }
  }

  public class Left2CargoSteal extends SequentialCommandGroup {
    public Left2CargoSteal() {
      addCommands(
        new InstantCommand(() -> { RobotContainer.DRIVETRAIN.resetPose(GeneratedPaths.LeftGrab_LeftCargo.getInitialPose()); }), 
        new DriveTrajectory(GeneratedPaths.LeftGrab_LeftCargo),
        new DriveTrajectory(GeneratedPaths.LeftCargo_Steal)
      );
    }
  }

  public class Mid4Cargo extends SequentialCommandGroup {
    public Mid4Cargo() {
      addCommands(
        new InstantCommand(() -> { RobotContainer.DRIVETRAIN.resetPose(GeneratedPaths.MidStart_MidCargo.getInitialPose()); }), 
        new DriveTrajectory(GeneratedPaths.MidStart_MidCargo),
        new DriveTrajectory(GeneratedPaths.MidCargo_Terminal)
      );
    }
  }

  public class Right3Cargo extends SequentialCommandGroup {
    public Right3Cargo() {
      addCommands(
        new InstantCommand(() -> { RobotContainer.DRIVETRAIN.resetPose(GeneratedPaths.Right_RightCargo.getInitialPose()); }), 
        new DriveTrajectory(GeneratedPaths.Right_RightCargo),
        new DriveTrajectory(GeneratedPaths.RightCargo_MidCargo)
      );
    }
  }

  public class Right5Cargo_GrabFirst extends SequentialCommandGroup {
    public Right5Cargo_GrabFirst() {
      addCommands(
        new InstantCommand(() -> { RobotContainer.DRIVETRAIN.resetPose(GeneratedPaths.Right_RightCargo.getInitialPose()); }), 
        new DriveTrajectory(GeneratedPaths.Right_RightCargo),
        new DriveTrajectory(GeneratedPaths.RightCargo_MidCargo),
        new DriveTrajectory(GeneratedPaths.MidCargoFromRight_Terminal)
      );
    }
  }

  public class Right5Cargo_ShootFirst extends SequentialCommandGroup {
    public Right5Cargo_ShootFirst() {
      addCommands(
        new InstantCommand(() -> { RobotContainer.DRIVETRAIN.resetPose(GeneratedPaths.Right_RightCargo_MidCargo.getInitialPose()); }), 
        new DriveTrajectory(GeneratedPaths.Right_RightCargo_MidCargo),
        new DriveTrajectory(GeneratedPaths.MidCargoFromRight_Terminal)
      );
    }
  }

}
